In [1]:
# Task 1

import numpy as np


even_numbers = np.arange(2, 34, 2)


X = even_numbers.reshape(4, 4)

print(X)


[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [3]:
# Task 2

import numpy as np

X = np.arange(1, 26).reshape(5, 5)

Y = X[X % 2 != 0]

print("Original 5x5 ndarray:")
print(X)
print("\nArray with only odd numbers:")
print(Y)


Original 5x5 ndarray:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]

Array with only odd numbers:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


In [6]:
import numpy as np

X = np.arange(1, 5) * np.ones((4, 1))

print(X)


[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [7]:
# Task 4

from google.colab import drive
drive.mount('/NumPy.ipynb')
import numpy as np

# Create a 1000x20 ndarray with random integers in the range [0, 5001)
X = np.random.randint(0, 5001, size=(1000, 20))
# Print the shape of X
print(X.shape)

# Calculate the average of the values in each column of X
ave_cols = np.mean(X, axis=0)

# Calculate the standard deviation of the values in each column of X
std_cols = np.std(X, axis=0)


print("Shape of ave_cols:", ave_cols.shape)
print("Shape of std_cols:", std_cols.shape)

# Mean normalize X
X_norm = (X - ave_cols) / std_cols

print("Mean normalized X:")
print(X_norm)

# Print the average of all the values of X_norm
ave_all_values = np.mean(X_norm)
print("Average of all values in X_norm:", ave_all_values)

# Print the average of the minimum value in each column of X_norm
ave_min_values = np.mean(np.min(X_norm, axis=0))
print("Average of minimum values in each column of X_norm:", ave_min_values)

# Print the average of the maximum value in each column of X_norm
ave_max_values = np.mean(np.max(X_norm, axis=0))
print("Average of maximum values in each column of X_norm:", ave_max_values)

# We create a random permutation of integers 0 to 4
np.random.permutation(5)

# Create a random permutation of row indices of X_norm
row_indices = np.random.permutation(X_norm.shape[0])

print("Random permutation of row indices:", row_indices)

# Define the ratios for training, cross-validation, and test sets
train_ratio = 0.6
cross_val_ratio = 0.2
test_ratio = 0.2

# Calculate the sizes of each set based on the ratios
num_rows = X_norm.shape[0]
num_train = int(train_ratio * num_rows)
num_cross_val = int(cross_val_ratio * num_rows)
num_test = int(test_ratio * num_rows)

# Use row_indices to split the data into sets
X_train = X_norm[row_indices[:num_train]]
X_crossVal = X_norm[row_indices[num_train:num_train + num_cross_val]]
X_test = X_norm[row_indices[num_train + num_cross_val:]]

print("X_train shape:", X_train.shape)
print("X_crossVal shape:", X_crossVal.shape)
print("X_test shape:", X_test.shape)

Mounted at /NumPy.ipynb
(1000, 20)
Shape of ave_cols: (20,)
Shape of std_cols: (20,)
Mean normalized X:
[[ 1.45609327e+00  5.36947665e-01  5.45527023e-01 ...  7.97501811e-01
  -1.16149073e-01  4.65478401e-01]
 [ 6.39931464e-02 -7.20690828e-01 -9.82516898e-01 ...  1.64591166e+00
  -4.35401999e-01  2.74766626e-01]
 [-3.02607239e-01  5.54035802e-02 -1.33262098e+00 ... -6.48729795e-01
  -1.25019099e+00  9.59007779e-04]
 ...
 [ 5.95318370e-01 -1.15232304e+00 -3.28338350e-01 ... -3.87786813e-01
  -1.66452577e+00  1.86679582e-02]
 [ 1.49509871e-01  1.28513923e-01  1.58607542e+00 ...  5.47117355e-02
  -4.46506449e-01 -1.11742933e+00]
 [-5.23408618e-01 -1.55232098e+00  1.28060612e+00 ...  1.39532356e+00
  -1.54320618e-01  6.24177841e-01]]
Average of all values in X_norm: -2.7000623958883807e-17
Average of minimum values in each column of X_norm: -1.732606696897588
Average of maximum values in each column of X_norm: 1.725742749168613
Random permutation of row indices: [372 379 596  70 131 799 68